Repository susanghan/cafehub-spring, pull requests merged in 2022-08, with the labels that each got.

#13 [Style] 기본적인 폴더 구조 정리
  build.gradle
  src/main/java/com/cafehub/cafehubspring/CafehubSpringApplication.java
  src/main/java/com/cafehub/cafehubspring/common/BaseTimeEntity.java
  src/main/java/com/cafehub/cafehubspring/common/DefaultResponseDto.java
  src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
  src/main/java/com/cafehub/cafehubspring/controller/CafeController.java
  src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
  src/main/java/com/cafehub/cafehubspring/domain/Photo.java
  src/main/java/com/cafehub/cafehubspring/dto/CafeSaveRequestDto.java
  src/main/java/com/cafehub/cafehubspring/dto/CafeSaveResponseDto.java
  src/main/java/com/cafehub/cafehubspring/exception/DefaultExceptionResponseDto.java
  src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
  src/main/java/com/cafehub/cafehubspring/repository/PhotoRepository.java
  src/main/java/com/cafehub/cafehubspring/service/CafeService.java
  src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
  src/main/resources/application.yml
Labels: Status: To Do

#15 [Fix] MySQL 연동을 위한 config 수정
  build.gradle
  src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
  src/main/resources/application.yml
Labels: Status: Reviewing

#16 [Feat] Swagger 띄우기
  build.gradle
  src/main/java/com/cafehub/cafehubspring/config/SwaggerConfiguration.java
Labels: Status: Reviewing

#18 [Fix] BaseTimeEntity에 Id 필드 제거
  src/main/java/com/cafehub/cafehubspring/common/BaseTimeEntity.java
Labels: Status: Reviewing

#19 [Feat] Photo Entity, Photo Repository 구현
  src/main/java/com/cafehub/cafehubspring/domain/Photo.java
  src/main/java/com/cafehub/cafehubspring/repository/PhotoRepository.java
Labels: Status: Reviewing

#20 [Feat] S3 Configuration 구현
  build.gradle
  src/main/java/com/cafehub/cafehubspring/config/S3Configuration.java
  src/main/resources/application.yml
Labels: Status: Reviewing

#21 [Feat] Cafe Entity, Cafe Repository 구현
  src/main/java/com/cafehub/cafehubspring/domain/Cafe.java
  src/main/java/com/cafehub/cafehubspring/repository/CafeRepository.java
Labels: Status: Pending, Status: Reviewing

#24 [Feat] Photo 업로드, 삭제 서비스 구현
  src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
Labels: Status: Pending, Status: Reviewing

#23 [Feat] Cafe 저장 Request DTO
  src/main/java/com/cafehub/cafehubspring/dto/CafeSaveRequestDto.java
Labels: Status: Pending, Status: Reviewing

#27 [Fix] amazonS3를 amzonS3Client로 변경
  src/main/java/com/cafehub/cafehubspring/service/PhotoService.java
Labels: Status: Reviewing

#30 [Feat] 주소를 이용해 위도, 경도 구하기
  build.gradle
  src/main/java/com/cafehub/cafehubspring/service/CafeService.java
  src/main/resources/application.yml
Labels: Status: Reviewing
